# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_plot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 982)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.show_data_scrollArea = QtWidgets.QScrollArea(self.widget)
        self.show_data_scrollArea.setWidgetResizable(True)
        self.show_data_scrollArea.setObjectName("show_data_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 782))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.show_data_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.show_data_scrollArea)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_plot_one = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_plot_one.setGeometry(QtCore.QRect(10, 10, 106, 30))
        self.pushButton_plot_one.setObjectName("pushButton_plot_one")
        self.pushButton_plot_multi = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_plot_multi.setGeometry(QtCore.QRect(150, 10, 106, 30))
        self.pushButton_plot_multi.setObjectName("pushButton_plot_multi")
        self.pushButton_3d = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3d.setGeometry(QtCore.QRect(10, 60, 106, 30))
        self.pushButton_3d.setObjectName("pushButton_3d")
        self.pushButton_reset = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_reset.setGeometry(QtCore.QRect(150, 60, 106, 30))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.frame_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setObjectName("frame_plot")
        self.horizontalLayout.addWidget(self.frame_plot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 28))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.file_menu.addAction(self.action)
        self.menubar.addAction(self.file_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_plot_one.clicked.connect(MainWindow.plot_2d_one)
        self.pushButton_plot_multi.clicked.connect(MainWindow.plot_2d_multi)
        self.pushButton_3d.clicked.connect(MainWindow.plot_3d)
        self.menubar.triggered['QAction*'].connect(MainWindow.openFile)
        self.pushButton_reset.clicked.connect(MainWindow.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_plot_one.setText(_translate("MainWindow", "plot one"))
        self.pushButton_plot_multi.setText(_translate("MainWindow", "plot multi"))
        self.pushButton_3d.setText(_translate("MainWindow", "plot 3d"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.file_menu.setTitle(_translate("MainWindow", "文件"))
        self.action.setText(_translate("MainWindow", "打开"))

